### PR TITLE
Update sample to use tag instead of digest reference.

### PR DESCRIPTION
**Pull request by thomasyip-msft**
## Purpose

Tag support is enabled with latest CPA tool, updating the documentation to reflect the change. Tag support is enabled starting cpa tool version 1.2.1

- This reduces the modifications required for ISV to change their helm charts to adopt to our CNAB model
- Tag is being resolved in cpa buildbundle time. Internally we will update the registry/repositiory:tag during extension registration to match the generated tag inside Microsoft Marketplace ACR.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by KeithMnemonic** [comment]
Will you also be updating https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart

image

**Comment by thomasyip-msft** [comment]
> Will you also be updating https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart
> 
> image

Yes we will.

**Comment by KeithMnemonic** [comment]
> > Will you also be updating https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart
> > image
> 
> Yes we will.

Thank you. 

> > Will you also be updating https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart
> > image
> 
> Yes we will.

Thank you. Also since the example is supporting "latest" does that mean if in image is updated, it will get automatically pulled when the "reconciler runs on the CNAB bundle" or do you still need to push a new CNAB ? For example. if you publish CNAB 1.0.0 using 'latest' which points to 1.0.0 of the image and the image is updated such that 'latest' is now 1.0.1 . Do you need to publish a new CNAB, 1.0.1 or will the existing infrastructure have the ability to automatically update the original 1.0.0 CNAB?

**Comment by thomasyip-msft** [comment]
> > > Will you also be updating https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart
> > > image
> > 
> > 
> > Yes we will.
> 
> Thank you.
> 
> > > Will you also be updating https://learn.microsoft.com/en-us/partner-center/marketplace/azure-container-technical-assets-kubernetes?tabs=linux#update-the-helm-chart
> > > image
> > 
> > 
> > Yes we will.
> 
> Thank you. Also since the example is supporting "latest" does that mean if in image is updated, it will get automatically pulled when the "reconciler runs on the CNAB bundle" or do you still need to push a new CNAB ? For example. if you publish CNAB 1.0.0 using 'latest' which points to 1.0.0 of the image and the image is updated such that 'latest' is now 1.0.1 . Do you need to publish a new CNAB, 1.0.1 or will the existing infrastructure have the ability to automatically update the original 1.0.0 CNAB?

You still need to push a new CNAB. tag is resolved during the CNAB build time where it is being bundled. So when you wish to include the latest latest, you will need to increment the manifest version to 1.0.1 and push it through partner center for customer to upgrade their extensions.

**Review by RamyasreeChakka — APPROVED** [review]

**Review by RamyasreeChakka — APPROVED** [review]

**Pull request merged**
